language: node_js
sudo: false
node_js:
- 4
env:
  global:
  - SAUCE_USERNAME=aria-listbox
  - secure: em6BAcYD/fkTXSQGEoBSFTvnY9Iw8j3/+Nb4+F7Q9cUvq9hO/Wa7AvRCMitHY9jjAgrrLG97D3APN6vzNUqW+resCEjmSoTNjf0dYCqdrMUKZeC55mv6g6ajoH4//a6dV/zhTn/K/Rz/MoOYOoY7nnJsBeJzxoCLqBUrT66xmX73YmS2zYjlhthI6CXfKi0+9D5jWQV5bPo6Ay4s+rG1wjqo84fPjacY50jehxeDhUYsB12cn71SnpJZZT53eehxYEN9NKyoXWlyrMFX+zA4UIusL1IdzumXEeup2gg2gdMivnr2JCPZP6bvq6+0Tl1EMV98OUYVgCMZkT10vy2VeENxdoNoHwmVopj6drNV9W7VRoYH1JEL7uHw+Cny0y6Tscflfvp8R4fBgR8CABIz9Xy2j6NN5VIfHtLOsB9WZV1LrAkHd+vdTmB2h95qCgfa7Y5SqPOcCQHvVgI3jVt9G1uxO7WvVfrRHSbo8keP77495mSzN8VIzpgyQ7pi7WhERzhNKJKT+XjvbBT7PIsdLqmz72imJnLv6uhQsGmBbnh7F2EAuccXQJuTTT48TBW1dFFkRWPg7uCa3JTS65DYJFerDKD6HTkur7TS15RYk0W1aqVFP66xAB2+FSSiGt/UWWri29sHju+IHCPoK5jb+ipxoOnJIuOIoQE/XR/ocrQ=
script: npm test
